---

- name: creates directories
  file: 
    state: directory
    path: '{{ item }}'
  with_items:
    - '/etc/consul-template/config.d/'
    - '/etc/consul-template/templates/'


- name: uploads configuration files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
  with_items:
    - { src: 'config.conf.j2', dest: '/etc/consul-template/config.d/config.conf' }
  notify:
    # restart consul if configuration changes
    - restart consul-template


- name: retrieves and launches 'consul-template' image
  docker:
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_consul_template_image }}'
    volumes:
      # to listen docker events
      - '/var/run/docker.sock:/tmp/docker.sock'
      - '/etc/consul-template:/consul-template'
      # to support nginx
      - '/var/www:/var/www'
    hostname: '{{ ansible_hostname }}'
    command: '/usr/local/bin/consul-template -config /consul-template/config.d/config.conf'
    name: consul-template
    state: started
    # will be checked for a newer version of the image each time the task executes
    pull: always
    # try to restart if the container exits
    restart_policy: always
    # it will try to restart 3 times before giving up
    restart_policy_retry: 3
