---
# See: https://github.com/gliderlabs/registrator

- name: retrieves and launches 'consul-registrator' image
  docker:
    docker_api_version: '{{ docker_api_version }}'
    image: '{{ docker_consul_registrator_image }}'
    volumes:
      # to listen docker events
      - '/var/run/docker.sock:/tmp/docker.sock'
    hostname: '{{ ansible_hostname }}'
    name: consul-registrator
    command: 'consul://{{ ansible_eth0.ipv4.address }}:8500'
    state: started
    # will be checked for a newer version of the image each time the task executes
    pull: always
    # try to restart if the container exits
    restart_policy: always
    # it will try to restart 3 times before giving up
    restart_policy_retry: 3
